### ISSUE TITLE
Fix the semantic vector strategy

### ISSUE THREAD

**Issue by pdhoolia** [pdhoolia/se-agent#27]
Current implementation of semantic vector strategy seems to have an overly complex design.

Project seems to maintain an instance of semantic vector localization strategy, which seems to manage various semantic vector collections for the project.
While handling issue events, this instance of localization strategy is fetched and used.
This seems to be the wrong dependency structure without the right kind of separation of concerns.

Following code refactoring is proposed:
1. Separate the vector store management concern from localization strategy. Let the project be responsible for getting or creating a vector store. 
2. Rather than creating / loading the vector store as a member of the project during its construction, let's get or create it on demand. this will minimize the high memory requirement periods. Further only load the collection that is needed
3. Let SemanticVectorSearchLocalizer be constructed by injecting the vector store into it. Let it only have the localize method.
4. The methods to add / delete documents from the vector store are already available on langchain's VectorStore abstraction that we use. There is no point in replicating them once again. While adding documents to vector store (during semantic understanding) let's directly use the VectorStores' add_documents method.

**Comment by se-agent** [comment]
To address the issues and proposed refactoring, we can make several changes across the relevant files. Below are the suggestions:

1. **Separate Vector Store Management**: Move the responsibility of creating or fetching the vector store from the localization strategy to the project itself. This will help in managing dependencies better and adhere to the separation of concerns principle.

2. **On-Demand Vector Store Creation**: Modify the project to create or get the vector store only when needed. This will help in reducing memory usage by loading collections only when required.

3. **Inject Vector Store into Localizer**: Refactor the `SemanticVectorSearchLocalizer` to accept a vector store during its construction. This will simplify its responsibilities to just performing localization tasks.

4. **Leverage Existing VectorStore Methods**: Directly use the `add_documents` method from the VectorStore API, removing redundant code for document addition and deletion.

### Suggested Code Changes

1. **In `project.py`:**

   - Modify the method responsible for managing the vector store, creating it only when necessary.

   ```python
   class Project:
       def __init__(self, ...):
           ...
           self.vector_store = None

       def get_or_create_vector_store(self):
           if not self.vector_store:
               self.vector_store = self._initialize_vector_store()
           return self.vector_store

       def _initialize_vector_store(self):
           # Logic to initialize the vector store
           ...
   ```

2. **In `localize/semantic_vector_search.py`:**

   - Refactor `SemanticVectorSearchLocalizer` to take a vector store as a parameter during initialization.

   ```python
   class SemanticVectorSearchLocalizer:
       def __init__(self, vector_store):
           self.vector_store = vector_store

       def localize(self, ...):
           # Use the vector_store for localization
           ...
   ```

3. **In `localize/localization_strategy.py`:**

   - Remove any vector store management code, focusing solely on localization logic.

   ```python
   class LocalizationStrategy:
       def __init__(self, ...):
           # No vector store management here
           ...

       def some_method(self, ...):
           # Logic without vector store management
           ...
   ```

4. **Utilizing VectorStore API Directly:**

   - Ensure wherever documents are added to the vector store, the existing `add_documents` method from the VectorStore is used directly.

   ```python
   # Example usage
   vector_store.add_documents(documents)
   ```

These changes will streamline the architecture by clearly defining responsibilities, reducing complexity, and leveraging existing functionality in the `VectorStore` API. This refactoring will also allow for better memory management and more efficient use of resources.

**Comment by se-agent** [comment]
To address the issue of overly complex design in the current implementation of the semantic vector strategy, we can refactor the code according to the proposed changes. Here's a breakdown of the changes to implement:

1. **Separate Vector Store Management from Localization Strategy:**
   - Move the responsibility of managing the vector store out of the localization strategy. The `project.py` should handle the initialization and management of the vector store.

2. **On-Demand Vector Store Creation/Loading:**
   - Modify the project class to initialize or load the vector store on demand rather than during its construction. This can be achieved by creating a method in `project.py` for getting or creating the vector store.

3. **Dependency Injection for `SemanticVectorSearchLocalizer`:**
   - Refactor `SemanticVectorSearchLocalizer` to accept a vector store as a dependency during its construction. This change will simplify the class to focus on localization using the provided vector store.

4. **Use of Existing VectorStore Methods:**
   - Directly utilize the existing `add_documents` and `delete_documents` methods from the `VectorStore` class for document management.

Here's how these changes may look in the code:

### Changes in `project.py`

```python
class Project:
    def __init__(self, ...):
        # Remove vector store initialization from the constructor
        self.vector_store = None

    def get_or_create_vector_store(self):
        if not self.vector_store:
            # Logic to create or load vector store
            self.vector_store = VectorStore()  # Replace with actual initialization
        return self.vector_store
```

### Changes in `semantic_vector_search.py`

```python
class SemanticVectorSearchLocalizer:
    def __init__(self, vector_store):
        self.vector_store = vector_store

    def localize(self, query):
        # Localization logic using the vector store
        pass
```

### Refactoring Document Addition

Instead of duplicating methods, directly use the methods from `VectorStore`:

```python
def add_documents_to_vector_store(documents):
    vector_store = project.get_or_create_vector_store()
    vector_store.add_documents(documents)
```

These changes will lead to a cleaner, more modular design by separating concerns, reducing memory footprint by loading resources on demand, and leveraging existing functionalities provided by the `VectorStore`.

**Comment by se-agent** [comment]
To address the issues and refactor the code as proposed, we need to make several changes across the relevant files. Here's a breakdown of the changes:

### 1. Separate Vector Store Management from Localization Strategy

- **Remove vector store management from `SemanticVectorSearchLocalization`** and let `Project` handle it.

### 2. On-Demand Vector Store Management

Modify the `Project` class to handle vector stores on demand rather than initializing them during construction.

### 3. Inject Vector Store into Localization Strategy

Modify the `SemanticVectorSearchLocalization` to focus only on localization, with the vector store passed in as a dependency.

### 4. Use Existing VectorStore Methods

When adding or deleting documents, use the methods provided by the vector store directly.

---

### Code Refactoring

#### Changes in `localize/semantic_vector_search.py`

```python
class SemanticVectorSearchLocalization(LocalizationStrategy):
    def __init__(self, vector_store):
        self.vector_store = vector_store

    def localize(self, issue: Dict[str, str], top_n: int) -> List[str]:
        query = f"{issue['title']}: {issue['description']}"
        results = self.vector_store.similarity_search(query, k=top_n)
        return [result.metadata['filepath'] for result in results]
```

- **Removed**: Vector store management logic from the `SemanticVectorSearchLocalization` class constructor.
- **Modified**: `localize` method to use the injected `vector_store`.

#### Changes in `project.py`

```python
from langchain_milvus import Milvus

class Project:
    # ...

    def get_vector_store(self, collection_name: str) -> Milvus:
        if collection_name not in self.vector_stores:
            # Create a new Milvus vector store for the collection_name
            vector_store = Milvus(
                embedding_function=fetch_llm_for_task(TaskName.EMBEDDING),
                collection_name=collection_name,
                connection_args={"uri": self.get_vector_store_uri()}
            )
            self.vector_stores[collection_name] = vector_store
        return self.vector_stores[collection_name]

    def update_codebase_understanding(self, modified_files=None):
        # ...
        for file_path in modified_files:
            # ...
            if summary is not None:
                file_doc_path = os.path.join(self.package_details_folder, file_path + ".md")
                os.makedirs(os.path.dirname(file_doc_path), exist_ok=True)
                with open(file_doc_path, 'w') as f:
                    f.write(summary)
                # Add to vector store
                vector_store = self.get_vector_store(DEFAULT_VECTOR_TYPE)
                vector_store.add_documents([Document(page_content=summary, metadata={"filepath": file_path})])
                logger.info(f"Updated semantic summary for file: {file_path}")
            # ...

    def localize_issue(self, issue: Dict[str, str], top_n: int, collection_name: str=DEFAULT_VECTOR_TYPE) -> List[str]:
        vector_store = self.get_vector_store(collection_name)
        localizer = SemanticVectorSearchLocalization(vector_store)
        return localizer.localize(issue, top_n)
```

- **Added**: `get_vector_store` method to manage vector stores on demand.
- **Modified**: `update_codebase_understanding` to use the vector store directly for adding documents.
- **Added**: `localize_issue` method to create a `SemanticVectorSearchLocalization` instance with the appropriate vector store when needed.

These changes will help separate concerns and manage resources more efficiently by only loading necessary components on demand.
